<?php

namespace Container9Lvm2T1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xcmTVdq.App\Controller\ContactController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.xcmTVdq'] ?? $container->load('get_ServiceLocator_XcmTVdqService'));

        if (isset($container->privates['.service_locator.xcmTVdq.App\\Controller\\ContactController::edit()'])) {
            return $container->privates['.service_locator.xcmTVdq.App\\Controller\\ContactController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\ContactController::edit()', $container);

        if (isset($container->privates['.service_locator.xcmTVdq.App\\Controller\\ContactController::edit()'])) {
            return $container->privates['.service_locator.xcmTVdq.App\\Controller\\ContactController::edit()'];
        }

        return $container->privates['.service_locator.xcmTVdq.App\\Controller\\ContactController::edit()'] = $instance;
    }
}
