<?php

namespace Container9Lvm2T1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9qlfsFQ.App\Entity\Contact' shared service.
     *
     * @return \App\Entity\Contact
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9qlfsFQ": it needs an instance of "App\\Entity\\Contact" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
