<?php

namespace Container9Lvm2T1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductImageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Cm8d.57.App\Entity\ProductImage' shared service.
     *
     * @return \App\Entity\ProductImage
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Cm8d.57": it needs an instance of "App\\Entity\\ProductImage" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
