<?php

namespace Container9Lvm2T1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerdeleteImageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Cm8d.57.App\Controller\ProductController::deleteImage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'image' => ['privates', '.errored..service_locator.Cm8d.57.App\\Entity\\ProductImage', NULL, 'Cannot autowire service ".service_locator.Cm8d.57": it needs an instance of "App\\Entity\\ProductImage" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'image' => 'App\\Entity\\ProductImage',
            'em' => '?',
        ]))->withContext('App\\Controller\\ProductController::deleteImage()', $container);

        if (isset($container->privates['.service_locator.Cm8d.57.App\\Controller\\ProductController::deleteImage()'])) {
            return $container->privates['.service_locator.Cm8d.57.App\\Controller\\ProductController::deleteImage()'];
        }

        return $container->privates['.service_locator.Cm8d.57.App\\Controller\\ProductController::deleteImage()'] = $instance;
    }
}
