<?php

namespace Container9Lvm2T1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wEoPZVd.App\Controller\UserController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'em' => '?',
            'slugger' => '?',
        ]))->withContext('App\\Controller\\UserController::edit()', $container);

        if (isset($container->privates['.service_locator.wEoPZVd.App\\Controller\\UserController::edit()'])) {
            return $container->privates['.service_locator.wEoPZVd.App\\Controller\\UserController::edit()'];
        }

        return $container->privates['.service_locator.wEoPZVd.App\\Controller\\UserController::edit()'] = $instance;
    }
}
