<?php

namespace Container9T3gCsp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_UKIJHilService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.UKIJHil' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';

        $a = ($container->privates['texter.messenger.sms_handler'] ?? $container->load('getTexter_Messenger_SmsHandlerService'));

        if (isset($container->privates['.messenger.handler_descriptor.UKIJHil'])) {
            return $container->privates['.messenger.handler_descriptor.UKIJHil'];
        }

        $instance = new \Symfony\Component\Messenger\Handler\HandlerDescriptor($a, []);

        if (isset($container->privates['.messenger.handler_descriptor.UKIJHil'])) {
            return $container->privates['.messenger.handler_descriptor.UKIJHil'];
        }

        return $container->privates['.messenger.handler_descriptor.UKIJHil'] = $instance;
    }
}
