<?php

namespace Container9T3gCsp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OPjDmpcService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.OPjDmpc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'category' => ['privates', '.errored..service_locator.OPjDmpc.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.OPjDmpc": it needs an instance of "App\\Entity\\Category" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'category' => 'App\\Entity\\Category',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.OPjDmpc'])) {
            return $container->privates['.service_locator.OPjDmpc'];
        }

        return $container->privates['.service_locator.OPjDmpc'] = $instance;
    }
}
