<?php

namespace Container9T3gCsp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminRouteLoaderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'EasyCorp\Bundle\EasyAdminBundle\Router\AdminRouteLoader' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Router\AdminRouteLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/LoaderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/Loader.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Router/AdminRouteLoader.php';

        $a = ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Router\\AdminRouteGenerator'] ?? self::getAdminRouteGeneratorService($container));

        if (isset($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Router\\AdminRouteLoader'])) {
            return $container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Router\\AdminRouteLoader'];
        }

        $instance = new \EasyCorp\Bundle\EasyAdminBundle\Router\AdminRouteLoader($a);

        if (isset($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Router\\AdminRouteLoader'])) {
            return $container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Router\\AdminRouteLoader'];
        }

        return $container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Router\\AdminRouteLoader'] = $instance;
    }
}
