<?php

namespace Container9T3gCsp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllershowService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.9qlfsFQ.App\Controller\ContactController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9qlfsFQ.App\\Controller\\ContactController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contact' => ['privates', '.errored..service_locator.9qlfsFQ.App\\Entity\\Contact', NULL, 'Cannot autowire service ".service_locator.9qlfsFQ": it needs an instance of "App\\Entity\\Contact" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'contact' => 'App\\Entity\\Contact',
        ]))->withContext('App\\Controller\\ContactController::show()', $container);
    }
}
