<?php

namespace Container9T3gCsp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryControllereditService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.OPjDmpc.App\Controller\CategoryController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.OPjDmpc'] ?? $container->load('get_ServiceLocator_OPjDmpcService'));

        if (isset($container->privates['.service_locator.OPjDmpc.App\\Controller\\CategoryController::edit()'])) {
            return $container->privates['.service_locator.OPjDmpc.App\\Controller\\CategoryController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\CategoryController::edit()', $container);

        if (isset($container->privates['.service_locator.OPjDmpc.App\\Controller\\CategoryController::edit()'])) {
            return $container->privates['.service_locator.OPjDmpc.App\\Controller\\CategoryController::edit()'];
        }

        return $container->privates['.service_locator.OPjDmpc.App\\Controller\\CategoryController::edit()'] = $instance;
    }
}
