<?php

namespace Container9T3gCsp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryControllershowService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.Cm49tF9.App\Controller\CategoryController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cm49tF9.App\\Controller\\CategoryController::show()'] = ($container->privates['.service_locator.Cm49tF9'] ?? $container->load('get_ServiceLocator_Cm49tF9Service'))->withContext('App\\Controller\\CategoryController::show()', $container);
    }
}
