<?php

namespace Container9T3gCsp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerindexService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.Kd1lkYG.App\Controller\ProductController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'productRepository' => 'App\\Repository\\ProductRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\ProductController::index()', $container);

        if (isset($container->privates['.service_locator.Kd1lkYG.App\\Controller\\ProductController::index()'])) {
            return $container->privates['.service_locator.Kd1lkYG.App\\Controller\\ProductController::index()'];
        }

        return $container->privates['.service_locator.Kd1lkYG.App\\Controller\\ProductController::index()'] = $instance;
    }
}
