<?php

namespace Container9T3gCsp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductController2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\api\ProductController' shared autowired service.
     *
     * @return \App\Controller\api\ProductController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/api/ProductController.php';

        $container->services['App\\Controller\\api\\ProductController'] = $instance = new \App\Controller\api\ProductController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\api\\ProductController', $container));

        return $instance;
    }
}
