<?php

namespace Container9T3gCsp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductCrudControllerbatchDeleteService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.Zxs0ZZ9.App\Controller\Admin\ProductCrudController::batchDelete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zxs0ZZ9.App\\Controller\\Admin\\ProductCrudController::batchDelete()'] = ($container->privates['.service_locator.Zxs0ZZ9'] ?? $container->load('get_ServiceLocator_Zxs0ZZ9Service'))->withContext('App\\Controller\\Admin\\ProductCrudController::batchDelete()', $container);
    }
}
