<?php

namespace Container9T3gCsp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTexter_Messenger_SmsHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'texter.messenger.sms_handler' shared service.
     *
     * @return \Symfony\Component\Notifier\Messenger\MessageHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Messenger/MessageHandler.php';

        $a = ($container->privates['texter.transports'] ?? $container->load('getTexter_TransportsService'));

        if (isset($container->privates['texter.messenger.sms_handler'])) {
            return $container->privates['texter.messenger.sms_handler'];
        }

        $instance = new \Symfony\Component\Notifier\Messenger\MessageHandler($a);

        if (isset($container->privates['texter.messenger.sms_handler'])) {
            return $container->privates['texter.messenger.sms_handler'];
        }

        return $container->privates['texter.messenger.sms_handler'] = $instance;
    }
}
