<?php

namespace ContainerXLPQO6r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IHf39wm.App\Controller\ContactController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'entityManager' => '?',
            'mailer' => '?',
        ]))->withContext('App\\Controller\\ContactController::new()', $container);

        if (isset($container->privates['.service_locator.IHf39wm.App\\Controller\\ContactController::new()'])) {
            return $container->privates['.service_locator.IHf39wm.App\\Controller\\ContactController::new()'];
        }

        return $container->privates['.service_locator.IHf39wm.App\\Controller\\ContactController::new()'] = $instance;
    }
}
