<?php

namespace ContainerEl9qJIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M34Nym4Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.M34Nym4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'mapper' => ['privates', 'App\\Mapping\\ProductMapping', 'getProductMappingService', true],
        ], [
            'productRepository' => 'App\\Repository\\ProductRepository',
            'mapper' => 'App\\Mapping\\ProductMapping',
        ]);

        if (isset($container->privates['.service_locator.M34Nym4'])) {
            return $container->privates['.service_locator.M34Nym4'];
        }

        return $container->privates['.service_locator.M34Nym4'] = $instance;
    }
}
