<?php

namespace ContainerEl9qJIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cm49tF9Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.Cm49tF9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cm49tF9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'category' => ['privates', '.errored..service_locator.Cm49tF9.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.Cm49tF9": it needs an instance of "App\\Entity\\Category" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'category' => 'App\\Entity\\Category',
        ]);
    }
}
