<?php

namespace ContainerEl9qJIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiCategoryControllershowService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.qdlZVFa.App\Controller\api\ApiCategoryController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qdlZVFa.App\\Controller\\api\\ApiCategoryController::show()'] = ($container->privates['.service_locator.qdlZVFa'] ?? $container->load('get_ServiceLocator_QdlZVFaService'))->withContext('App\\Controller\\api\\ApiCategoryController::show()', $container);
    }
}
