<?php

namespace ContainerEl9qJIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryMappingService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Mapping\CategoryMapping' shared autowired service.
     *
     * @return \App\Mapping\CategoryMapping
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Mapping/CategoryMapping.php';

        return $container->privates['App\\Mapping\\CategoryMapping'] = new \App\Mapping\CategoryMapping();
    }
}
