<?php

namespace ContainerEl9qJIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllershowService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.M34Nym4.App\Controller\api\ProductController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.M34Nym4'] ?? $container->load('get_ServiceLocator_M34Nym4Service'));

        if (isset($container->privates['.service_locator.M34Nym4.App\\Controller\\api\\ProductController::show()'])) {
            return $container->privates['.service_locator.M34Nym4.App\\Controller\\api\\ProductController::show()'];
        }

        $instance = $a->withContext('App\\Controller\\api\\ProductController::show()', $container);

        if (isset($container->privates['.service_locator.M34Nym4.App\\Controller\\api\\ProductController::show()'])) {
            return $container->privates['.service_locator.M34Nym4.App\\Controller\\api\\ProductController::show()'];
        }

        return $container->privates['.service_locator.M34Nym4.App\\Controller\\api\\ProductController::show()'] = $instance;
    }
}
