<?php

namespace ContainerEl9qJIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductMappingService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Mapping\ProductMapping' shared autowired service.
     *
     * @return \App\Mapping\ProductMapping
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Mapping/ProductMapping.php';

        $a = ($container->privates['url_helper'] ?? self::getUrlHelperService($container));

        if (isset($container->privates['App\\Mapping\\ProductMapping'])) {
            return $container->privates['App\\Mapping\\ProductMapping'];
        }

        $instance = new \App\Mapping\ProductMapping(($container->privates['Vich\\UploaderBundle\\Templating\\Helper\\UploaderHelper'] ?? $container->load('getUploaderHelperService')), $a);

        if (isset($container->privates['App\\Mapping\\ProductMapping'])) {
            return $container->privates['App\\Mapping\\ProductMapping'];
        }

        return $container->privates['App\\Mapping\\ProductMapping'] = $instance;
    }
}
