<?php

namespace ContainerEl9qJIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaginationRuntimeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Knp\Bundle\PaginatorBundle\Twig\Extension\PaginationRuntime' shared service.
     *
     * @return \Knp\Bundle\PaginatorBundle\Twig\Extension\PaginationRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-paginator-bundle/src/Twig/Extension/PaginationRuntime.php';

        $a = ($container->privates['knp_paginator.helper.processor'] ?? $container->load('getKnpPaginator_Helper_ProcessorService'));

        if (isset($container->privates['Knp\\Bundle\\PaginatorBundle\\Twig\\Extension\\PaginationRuntime'])) {
            return $container->privates['Knp\\Bundle\\PaginatorBundle\\Twig\\Extension\\PaginationRuntime'];
        }

        $instance = new \Knp\Bundle\PaginatorBundle\Twig\Extension\PaginationRuntime($a, 'page', false);

        if (isset($container->privates['Knp\\Bundle\\PaginatorBundle\\Twig\\Extension\\PaginationRuntime'])) {
            return $container->privates['Knp\\Bundle\\PaginatorBundle\\Twig\\Extension\\PaginationRuntime'];
        }

        return $container->privates['Knp\\Bundle\\PaginatorBundle\\Twig\\Extension\\PaginationRuntime'] = $instance;
    }
}
