<?php

namespace ContainerEl9qJIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductImageCrudControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\ProductImageCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\ProductImageCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Contracts/Controller/CrudControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Controller/AbstractCrudController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/ProductImageCrudController.php';

        $instance = new \App\Controller\Admin\ProductImageCrudController();

        if (isset($container->services['App\\Controller\\Admin\\ProductImageCrudController'])) {
            return $container->services['App\\Controller\\Admin\\ProductImageCrudController'];
        }

        $container->services['App\\Controller\\Admin\\ProductImageCrudController'] = $instance;

        $instance->setContainer(($container->privates['.service_locator.t0DHw4I'] ?? $container->load('get_ServiceLocator_T0DHw4IService'))->withContext('App\\Controller\\Admin\\ProductImageCrudController', $container));

        return $instance;
    }
}
