<?php

namespace ContainerEl9qJIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRouting_Loader_Attribute_ServicesService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'routing.loader.attribute.services' shared service.
     *
     * @return \Symfony\Component\Routing\Loader\AttributeServicesLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/LoaderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/Loader.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/routing/Loader/AttributeServicesLoader.php';

        return $container->privates['routing.loader.attribute.services'] = new \Symfony\Component\Routing\Loader\AttributeServicesLoader(['App\\Controller\\CategoryController', 'App\\Controller\\ContactController', 'App\\Controller\\HomeController', 'App\\Controller\\ProductController', 'App\\Controller\\RegistrationController', 'App\\Controller\\SecurityController', 'App\\Controller\\UserController', 'App\\Controller\\api\\ApiCategoryController', 'App\\Controller\\api\\ProductController']);
    }
}
