<?php

namespace ContainerEl9qJIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_TwigComponent_ComponentStackService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'ux.twig_component.component_stack' shared service.
     *
     * @return \Symfony\UX\TwigComponent\ComponentStack
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/ComponentStack.php';

        return $container->privates['ux.twig_component.component_stack'] = new \Symfony\UX\TwigComponent\ComponentStack();
    }
}
