<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9T3gCsp\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9T3gCsp/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container9T3gCsp.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container9T3gCsp\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container9T3gCsp\App_KernelTestDebugContainer([
    'container.build_hash' => '9T3gCsp',
    'container.build_id' => '7a91af72',
    'container.build_time' => 1774950509,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9T3gCsp');
